version: "1"
services:
  flooder-job:
    type: job
    run: manual  # Manual Run Enable Karo
    build:  
      context: .  # Current directory se build karega
      dockerfile: Dockerfile  # Dockerfile use karega build ke liye
    resources:
      limits:
        cpu: 4000m  # 4 vCPU
        memory: 4096Mi  # 4GB RAM
    tasks:
      - name: Build & Run Flooder
        command: |
          sudo apt update && sudo apt install -y gcc python3
          pip install python-telegram-bot
          gcc m.c -o legacy
          python3 vps.py
